apiVersion: v1
kind: Namespace
metadata:
  name: egress
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: egress
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: egress-proxy
spec:
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: egress-proxy
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: proxy
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: egress
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: egress-proxy
data:
  nginx.conf: |-
    events {
    }
    http {
      include /etc/nginx/resolvers-data/resolvers.conf;

      server {
        listen     8080;

        location / {
          if ($host ~* "(.*)\.egress\.local") {
            set $real_host $1;
          }

          proxy_pass https://$real_host;
          proxy_set_header Host $real_host;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: egress
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: egress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: egress-proxy
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: egress-proxy
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx
      - name: resolvers-data
        emptyDir: {}
      initContainers:
        - name: setup-resolvers
          image: busybox:1.28
          command: ["sh", "-c", "echo resolver $(awk 'BEGIN{ORS=\" \"} $1==\"nameserver\" {print $2}' /etc/resolv.conf)\";\" > /etc/nginx/resolvers-data/resolvers.conf"]
          volumeMounts:
            - name: resolvers-data
              mountPath: /etc/nginx/resolvers-data
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
        - name: resolvers-data
          mountPath: /etc/nginx/resolvers-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . "/etc/resolv.conf"
        cache 30
        loop
        reload
        loadbalance
        rewrite name regex (.*)\.egress.local proxy.egress.svc.cluster.local
    } # STUBDOMAINS - Rancher specific change
